#!/bin/bash

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
        -f|--file)
      TOUCAN_FILE="$2"
      shift # past argument
      shift # past value
      ;;
    -s|--slug)
      TOUCAN_SLUG="$2"
      shift # past argument
      shift # past value
      ;;
    -a|--article)
      SWIFTINIT_ARTICLE="$2"
      shift # past argument
      shift # past value
      ;;
    --default)
      DEFAULT=YES
      shift # past argument
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters


#echo "INPUT  = ${INPUT}"
#echo "SEARCH PATH     = ${SEARCHPATH}"
#echo "DEFAULT         = ${DEFAULT}"
#echo "Number files in SEARCH PATH with EXTENSION:" $(ls -1 "${SEARCHPATH}"/*."${EXTENSION}" | wc -l)
#if [[ -n $1 ]]; then
#    echo "Last line of file specified as non-opt/last argument:"
#    tail -1 "$1"
#fi
#EOF

if [[ -z "${SWIFTINIT_ARTICLE}" ]]; then
    echo "⚠️ Not a SwiftInit page: ${TOUCAN_SLUG}."
    exit 0
fi

if [[ -z "${SWIFTINIT_ACCOUNT}" ]]; then
    echo "❌ No SwiftInit account is set: SWIFTINIT_ACCOUNT."
    exit 0
fi

if [[ -z "${SWIFTINIT_API_KEY}" ]]; then
    echo "❌ No SwiftInit api key is set: SWIFTINIT_API_KEY."
    exit 0
fi

echo "⏳ Rendering: ${SWIFTINIT_ARTICLE}."

curl "https://api.swiftinit.org/render/swift-on-server.site:preview/site/${SWIFTINIT_ARTICLE}?account=${SWIFTINIT_ACCOUNT}&api_key=${SWIFTINIT_API_KEY}" >> "${TOUCAN_FILE}"

echo "✅ Rendering: ${SWIFTINIT_ARTICLE}."
