name: Dispatch macOS and Linux Builds on new tag

on:
  push:
    tags:
      - 'v*'
      - '[0-9]*'

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}
      original_version: ${{ steps.extract.outputs.original_version }}
    steps:
      - name: Extract version from tag
        id: extract
        run: |
          RAW_VERSION="${GITHUB_REF#refs/tags/}"
          CLEAN_VERSION="${RAW_VERSION//-/.}"
          echo "Version: $CLEAN_VERSION"
          echo "VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
          echo "version=$CLEAN_VERSION" >> $GITHUB_OUTPUT

  linux:
    needs: prepare
    uses: ./.github/workflows/linux.yml
    with:
      version: ${{ needs.prepare.outputs.version }}
      run_rpm: true
      run_deb: true
      static_stdlib: true
    secrets: inherit

  macos:
    needs: prepare
    uses: ./.github/workflows/macos.yml
    with:
      version: ${{ needs.prepare.outputs.version }}
      run_pkg: true
      run_dmg: false
    secrets: inherit

  pr_for_formula:
    name: Create a PR for Homebrew Formula
    needs: [prepare, linux, macos]
    uses: ./.github/workflows/pr-for-formula.yml
    with:
      version: ${{ needs.prepare.outputs.version }}
      baseurl: https://github.com/toucansites/toucan/releases/download/${{ github.ref_name }}
      homepage: https://github.com/toucansites/toucan
      formulafile: toucan.rb
      formulaclass: Toucan
      repository: toucansites/homebrew-toucan
    secrets:
      HOMEBREW_TAP_PAT: ${{ secrets.HOMEBREW_TAP_PAT }}